require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BabyPicsController do

  # This should return the minimal set of attributes required to create a valid
  # BabyPic. As you add validations to BabyPic, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BabyPicsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all baby_pics as @baby_pics" do
      baby_pic = BabyPic.create! valid_attributes
      get :index, {}, valid_session
      assigns(:baby_pics).should eq([baby_pic])
    end
  end

  describe "GET show" do
    it "assigns the requested baby_pic as @baby_pic" do
      baby_pic = BabyPic.create! valid_attributes
      get :show, {:id => baby_pic.to_param}, valid_session
      assigns(:baby_pic).should eq(baby_pic)
    end
  end

  describe "GET new" do
    it "assigns a new baby_pic as @baby_pic" do
      get :new, {}, valid_session
      assigns(:baby_pic).should be_a_new(BabyPic)
    end
  end

  describe "GET edit" do
    it "assigns the requested baby_pic as @baby_pic" do
      baby_pic = BabyPic.create! valid_attributes
      get :edit, {:id => baby_pic.to_param}, valid_session
      assigns(:baby_pic).should eq(baby_pic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BabyPic" do
        expect {
          post :create, {:baby_pic => valid_attributes}, valid_session
        }.to change(BabyPic, :count).by(1)
      end

      it "assigns a newly created baby_pic as @baby_pic" do
        post :create, {:baby_pic => valid_attributes}, valid_session
        assigns(:baby_pic).should be_a(BabyPic)
        assigns(:baby_pic).should be_persisted
      end

      it "redirects to the created baby_pic" do
        post :create, {:baby_pic => valid_attributes}, valid_session
        response.should redirect_to(BabyPic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved baby_pic as @baby_pic" do
        # Trigger the behavior that occurs when invalid params are submitted
        BabyPic.any_instance.stub(:save).and_return(false)
        post :create, {:baby_pic => {}}, valid_session
        assigns(:baby_pic).should be_a_new(BabyPic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BabyPic.any_instance.stub(:save).and_return(false)
        post :create, {:baby_pic => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested baby_pic" do
        baby_pic = BabyPic.create! valid_attributes
        # Assuming there are no other baby_pics in the database, this
        # specifies that the BabyPic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BabyPic.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => baby_pic.to_param, :baby_pic => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested baby_pic as @baby_pic" do
        baby_pic = BabyPic.create! valid_attributes
        put :update, {:id => baby_pic.to_param, :baby_pic => valid_attributes}, valid_session
        assigns(:baby_pic).should eq(baby_pic)
      end

      it "redirects to the baby_pic" do
        baby_pic = BabyPic.create! valid_attributes
        put :update, {:id => baby_pic.to_param, :baby_pic => valid_attributes}, valid_session
        response.should redirect_to(baby_pic)
      end
    end

    describe "with invalid params" do
      it "assigns the baby_pic as @baby_pic" do
        baby_pic = BabyPic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BabyPic.any_instance.stub(:save).and_return(false)
        put :update, {:id => baby_pic.to_param, :baby_pic => {}}, valid_session
        assigns(:baby_pic).should eq(baby_pic)
      end

      it "re-renders the 'edit' template" do
        baby_pic = BabyPic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BabyPic.any_instance.stub(:save).and_return(false)
        put :update, {:id => baby_pic.to_param, :baby_pic => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested baby_pic" do
      baby_pic = BabyPic.create! valid_attributes
      expect {
        delete :destroy, {:id => baby_pic.to_param}, valid_session
      }.to change(BabyPic, :count).by(-1)
    end

    it "redirects to the baby_pics list" do
      baby_pic = BabyPic.create! valid_attributes
      delete :destroy, {:id => baby_pic.to_param}, valid_session
      response.should redirect_to(baby_pics_url)
    end
  end

end
